name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  project_name: "be-search-engine"
  FRONTEND_URL: ${{ vars.FRONTEND_URL}}
  INDEX_PATH: ${{ vars.INDEX_PATH}}
  LOCAL_DEVELOPMENT: ${{ vars.LOCAL_DEVELOPMENT}}
  PROJECT_ID: ${{ vars.PROJECT_ID }}
  SERVICE_ACCOUNT_SECRET_NAME: ${{ vars.SERVICE_ACCOUNT_SECRET_NAME }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and test
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.project_name }}:latest

  deploy:
    if: github.ref == 'refs/heads/main'
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.project_name }}
          image: docker.io/${{ secrets.DOCKER_USERNAME }}/${{ env.project_name }}:latest
          flags: "--port=8000"
          region: "us-central1"
          env_vars: |-
            FRONTEND_URL=${{ env.FRONTEND_URL }}
            INDEX_PATH=${{ env.INDEX_PATH }}
            LOCAL_DEVELOPMENT=${{ env.LOCAL_DEVELOPMENT }}
            PROJECT_ID=${{ env.PROJECT_ID }}
            SERVICE_ACCOUNT_SECRET_NAME=${{ env.SERVICE_ACCOUNT_SECRET_NAME }}
